services:
  - type: web
    name: patrimonio-app
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/patrimonio-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PGHOST
        value: <será definido no painel>
      - key: PGPORT
        value: 5432
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: <será definido no painel>
      - key: PGDATABASE
        value: railway
